name: gestion_paiements_app
description: "A new Flutter project."

publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dépendances de l'application
  http: ^1.1.0                 # Pour faire des requêtes HTTP
  provider: ^6.0.5             # Pour la gestion d'état
  shared_preferences: ^2.1.1   # Pour stocker token et infos utilisateur
  cupertino_icons: ^1.0.8      # Icônes Cupertino pour iOS
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Pour ajouter des assets/images si besoin
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Pour ajouter des polices personnalisées
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
